class PopulaAtividades < ActiveRecord::Migration
  def self.up
    execute "insert into atividades (codigo, atividade, observacao) values ('528','ABATEDOURO - INDUSTRIALIZACAO','Abate de animais, separação de vísceras e cortes de carnes. O mesmo que MATADOURO.');
insert into atividades (codigo, atividade, observacao) values ('340','ABRASIVO, ARTIGO - FABRICA','Comércio de lixas, esmeris, rebolos, etc...');
insert into atividades (codigo, atividade, observacao) values ('86','ABRASIVOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('175','ACADEMIAS','');
insert into atividades (codigo, atividade, observacao) values ('243','ACIDOS EM GERAL -  DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('476','ACIDOS EM GERAL - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('1','ACOUGUE','');
insert into atividades (codigo, atividade, observacao) values ('2','ACUCAR - DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('3','ADEGA','');
insert into atividades (codigo, atividade, observacao) values ('497','ADESIVO - FABRICA','Folhas, fitas ou rolos de papel ou plástico, com um ou ambos os lados impregnado de cola ou material abrasivo.');
insert into atividades (codigo, atividade, observacao) values ('176','ADUBO, DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('369','ADUBO, ORIGEM ANIMAL OU VEGETAL','');
insert into atividades (codigo, atividade, observacao) values ('370','ADUBO, ORIGEM MINERAL','');
insert into atividades (codigo, atividade, observacao) values ('177','AEROPORTO','');
insert into atividades (codigo, atividade, observacao) values ('4','AGENCIA CORREIO COM MERCADORIAS','');
insert into atividades (codigo, atividade, observacao) values ('5','AGENCIA CORREIO SEM MERCADORIAS','');
insert into atividades (codigo, atividade, observacao) values ('502','AGROPECUARIO, PRODUTOS - LOJA E DEPOSITO','Comércio de sementes, arreios, selas, adubos, fertilizantes, agrotóxicos, cordas e demais artigos dos gênero utilizado em fazendas, sitios, chácaras, ranchos, etc...');
insert into atividades (codigo, atividade, observacao) values ('6','AGUA - DEPOSITO/LOJA','');
insert into atividades (codigo, atividade, observacao) values ('301','AGUA, EXTRACAO E ENGARRAFAMENTO','');
insert into atividades (codigo, atividade, observacao) values ('395','ALGODAO - TECELAGEM','');
insert into atividades (codigo, atividade, observacao) values ('302','ALIMENTO PARA ANIMAIS - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('7','ALIMENTO PARA ANIMAIS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('8','ALIMENTO, CONSERVAS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('178','ANIMAL, COMERCIO','');
insert into atividades (codigo, atividade, observacao) values ('117','ARMARINHO - LOJA E DEPOSITO','Comércio de linha, lã, botão, fivela, zíper, demais acessórios e artigos para confecção de roupas. O mesmo que AVIAMENTOS.');
insert into atividades (codigo, atividade, observacao) values ('303','ARROZ - BENEFICIAMENTO E ENGENHO','');
insert into atividades (codigo, atividade, observacao) values ('372','ASFALTO - USINA','');
insert into atividades (codigo, atividade, observacao) values ('40','ASILO/ ALBERGUE/CRECHE','');
insert into atividades (codigo, atividade, observacao) values ('529','AUTOMOVEL - AUTO-ELETRICO','');
insert into atividades (codigo, atividade, observacao) values ('543','AUTOMÓVEL - CONCESSIONÁRIA','Loja de venda de veículos representando um fabricante específico (Marca), com comércio de peças acessórios, com oficina de assistência técnica e manutenção em geral.');
insert into atividades (codigo, atividade, observacao) values ('143','AUTOMOVEL - LOJA, DEPOSITO E LOCADORA','');
insert into atividades (codigo, atividade, observacao) values ('525','AUTOMOVEL - MECANICA E FUNILARIA','');
insert into atividades (codigo, atividade, observacao) values ('527','AUTOMOVEL - TAPECARIA','');
insert into atividades (codigo, atividade, observacao) values ('526','AUTOMOVEL - VIDROS E SOM, INSTALACAO','');
insert into atividades (codigo, atividade, observacao) values ('142','AUTO-PECAS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('491','AVIAMENTOS - LOJA E DEPOSITO','Comércio de linha, lã, botão, fivela, zíper, demais acessórios e artigos para confecção de roupas. O mesmo que ARMARINHO.');
insert into atividades (codigo, atividade, observacao) values ('179','AVICOLA - LOJA E DEPOSITO','Comércio de carne de aves nos mais variados cortes, miúdos e ovos, podendo, inclusive, comercializar aves vivas.');
insert into atividades (codigo, atividade, observacao) values ('304','BALA COMESTIVEL - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('21','BALAS/CARAMELOS/ DOCES - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('10','BAR','');
insert into atividades (codigo, atividade, observacao) values ('180','BARBEARIA','');
insert into atividades (codigo, atividade, observacao) values ('148','BARCO - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('119','BAZAR','Comércio dos mais variados artigos de louça, vidro, metal, cerâmica, plástico, e demais artigos para decoração e presentes.');
insert into atividades (codigo, atividade, observacao) values ('305','BEBIDA ALCOOLICA - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('474','BEBIDAS - DISTRIBUIDORA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('181','BIBLIOTECA','');
insert into atividades (codigo, atividade, observacao) values ('145','BICICLETA - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('146','BICICLETA - OFICINA','');
insert into atividades (codigo, atividade, observacao) values ('120','BIJOUTERIA - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('343','BILHAR - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('182','BILHAR, SALAO','');
insert into atividades (codigo, atividade, observacao) values ('306','BISCOITO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('307','BOLACHA - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('11','BOLACHA/BISCOITO - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('185','BOLICHE, SALAO','');
insert into atividades (codigo, atividade, observacao) values ('398','BOLSA - FABRICA (QUALQUER MATERIAL)','');
insert into atividades (codigo, atividade, observacao) values ('152','BOLSAS/CINTOS/CONGENERES-LOJA/ DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('308','BOMBOM - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('12','BOMBONIERE - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('399','BORDADO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('432','BORRACHA - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('431','BORRACHA, ARTIGO  - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('162','BORRACHAS,ARTIGOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('400','BOTAO - FABRICA (QUALQUER MATERIAL)','');
insert into atividades (codigo, atividade, observacao) values ('147','BOTE - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('13','BOUTIQUE DE CARNES','');
insert into atividades (codigo, atividade, observacao) values ('14','BOUTIQUE DE PAES','');
insert into atividades (codigo, atividade, observacao) values ('121','BOUTIQUE DE ROUPAS','');
insert into atividades (codigo, atividade, observacao) values ('122','BRECHO','Comércio de Roupas usadas.');
insert into atividades (codigo, atividade, observacao) values ('186','BRINQUEDO, LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('15','BUFFET','Salão de festas de qualquer tipo, sem fabricação de alimentos, com local específico para aquecimento de alimentos a serem servidos no evento.');
insert into atividades (codigo, atividade, observacao) values ('188','CABELEIREIRO','');
insert into atividades (codigo, atividade, observacao) values ('309','CACAU - USINA E PREPARACAO','');
insert into atividades (codigo, atividade, observacao) values ('401','CADARCO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('310','CAFE - BENEFICIAMENTO E ENGENHO','');
insert into atividades (codigo, atividade, observacao) values ('311','CAFE - TORREFACAO E MOAGEM','');
insert into atividades (codigo, atividade, observacao) values ('312','CAFE SOLUVEL','');
insert into atividades (codigo, atividade, observacao) values ('16','CAFETERIA - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('402','CALCADO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('123','CALCADO - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('124','CAMA/MESA/BANHO, ARTIGOS-LOJA/DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('17','CAMARA FRIGORIFICA','Local que produz e conserva o frio com a finalidade de conservar produtos alimentícios ou substâncias que necessitam se manter em baixas temperaturas. O mesmo que FRIGORÍFICO.');
insert into atividades (codigo, atividade, observacao) values ('420','CANETA - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('313','CARAMELO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('433','CARIMBO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('190','CART, PISTA','');
insert into atividades (codigo, atividade, observacao) values ('53','CARTORIO','');
insert into atividades (codigo, atividade, observacao) values ('427','CARTUCHO/FITA PARA IMPRESSAO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('54','CASA DE BANHOS','');
insert into atividades (codigo, atividade, observacao) values ('18','CASA DE CARNES','');
insert into atividades (codigo, atividade, observacao) values ('193','CASA DE SHOW E ESPETACULOS','');
insert into atividades (codigo, atividade, observacao) values ('194','CASSINO','');
insert into atividades (codigo, atividade, observacao) values ('314','CASTANHA DO PARA - BENEFICIAMENTO','');
insert into atividades (codigo, atividade, observacao) values ('163','CELULOSE - DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('434','CELULOSE - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('195','CEMITERIO, VERTICAL','');
insert into atividades (codigo, atividade, observacao) values ('422','CERAMICA, ARTIGO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('153','CERAMICA, ARTIGOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('19','CEREAIS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('315','CEREAL - PREPARACAO, EXTRACAO E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('316','CERVEJA E REFRIGERANTE - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('403','CHAPEU - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('125','CHAPEU - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('196','CHARUTARIA','');
insert into atividades (codigo, atividade, observacao) values ('436','CHARUTO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('88','CHAVEIRO','');
insert into atividades (codigo, atividade, observacao) values ('317','CHOCOLATE - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('20','CHOCOLATES/BOMBONS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('437','CIGARRO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('197','CIGARRO, LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('447','CIMENTO, ARTIGO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('198','CIMENTO/ GESSO,  LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('448','CIMENTO/GESSO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('520','CIMENTO/GESSO, ARTIGO - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('61','CINE/FOTO/SOM - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('62','CINEMA','');
insert into atividades (codigo, atividade, observacao) values ('63','CINEMATOGRAFIA, ARTIGO - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('64','CINEMATOGRAFIA, ESTUDIOS','');
insert into atividades (codigo, atividade, observacao) values ('405','CINTO - FABRICA (QUALQUER MATERIAL)','');
insert into atividades (codigo, atividade, observacao) values ('344','CIRURGICO, ARTIGO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('41','CIRURGICOS, ARTIGOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('200','CLUBE','');
insert into atividades (codigo, atividade, observacao) values ('377','COLA SEM INFLAMAVEL - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('421','COMPACT DISC (CD) - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('318','CONDIMENTO - PREPARACAO E EMBALAGEM','');
insert into atividades (codigo, atividade, observacao) values ('43','CONSULTORIO DENTARIO','');
insert into atividades (codigo, atividade, observacao) values ('531','CONSULTORIO E CLINICA, COM IMAGEM','');
insert into atividades (codigo, atividade, observacao) values ('530','CONSULTORIO E CLINICA, ESTETICA','');
insert into atividades (codigo, atividade, observacao) values ('42','CONSULTORIO MEDICO','');
insert into atividades (codigo, atividade, observacao) values ('127','CONVENIENCIA - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('65','COPIADORA','');
insert into atividades (codigo, atividade, observacao) values ('449','CORDOARIA - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('102','COSMETICO - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('154','COURO E PELES - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('423','COURO, ARTIGO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('487','COZINHA INDUSTRIAL','Preparação de refeições acondicionadas em recipinetes e/ou embalagens apropriadas com produção em larga escala.');
insert into atividades (codigo, atividade, observacao) values ('201','CREMATORIO','');
insert into atividades (codigo, atividade, observacao) values ('424','CRISTAL - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('155','CRISTAL, ARTIGOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('345','CUTELARIA','Fabricação e/ou confecção de objetos ou ferramentas de corte ou instrumentos/artigos cortantes em geral.');
insert into atividades (codigo, atividade, observacao) values ('55','DELEGACIA','');
insert into atividades (codigo, atividade, observacao) values ('346','DENTARIO, APARELHO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('44','DENTARIOS, ARTIGOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('426','DISCO (VINIL) - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('239','DISCOS, FITAS E CD, LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('203','DIVERSAO, ELETRONICA','');
insert into atividades (codigo, atividade, observacao) values ('319','DOCE - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('506','DOCERIA - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('105','DROGARIA','');
insert into atividades (codigo, atividade, observacao) values ('205','EDIFICIO, DESOCUPADO','');
insert into atividades (codigo, atividade, observacao) values ('336','ELETRICO, ARTIGO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('521','ELETRO-ELETRONICO, APARELHO-OFICINA','');
insert into atividades (codigo, atividade, observacao) values ('66','ELETRO-ELETRONICO,APARELHO-LOJA/DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('337','ELETRONICO, ARTIGO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('22','EMPORIO','');
insert into atividades (codigo, atividade, observacao) values ('67','ESCOLA DE INFORMATICA','');
insert into atividades (codigo, atividade, observacao) values ('56','ESCOLA PARTICULAR','');
insert into atividades (codigo, atividade, observacao) values ('57','ESCOLA PUBLICA','');
insert into atividades (codigo, atividade, observacao) values ('45','ESCRITORIO','');
insert into atividades (codigo, atividade, observacao) values ('510','ESCRITORIO - TRANSMISSAO ELETRONICA','Local com grande quantidade de micro computadores e equipamentos de telefonia, para contatos externos, visando vender ou informar através de meios eletrônicos. Call-Center, provedor de informática, televendas, etc...');
insert into atividades (codigo, atividade, observacao) values ('347','ESMERIL - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('128','ESPORTE, ARTIGOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('210','ESTACAO, FERROVIARIA','');
insert into atividades (codigo, atividade, observacao) values ('206','ESTACAO, RODOVIARIA','');
insert into atividades (codigo, atividade, observacao) values ('207','ESTACIONAMENTO','');
insert into atividades (codigo, atividade, observacao) values ('348','ESTALEIRO','');
insert into atividades (codigo, atividade, observacao) values ('129','ESTAMPARIA DE ROUPAS/TECIDOS','');
insert into atividades (codigo, atividade, observacao) values ('69','ESTUDIO DE GRAVACAO - IMAGEM','');
insert into atividades (codigo, atividade, observacao) values ('70','ESTUDIO DE GRAVACAO - SOM','');
insert into atividades (codigo, atividade, observacao) values ('68','ESTUDIO FOTOGRAFICO','');
insert into atividades (codigo, atividade, observacao) values ('208','EVENTOS E FEIRAS, SALAO','');
insert into atividades (codigo, atividade, observacao) values ('209','EXPOSICOES','');
insert into atividades (codigo, atividade, observacao) values ('349','FABRICA EM DESMONTAGEM SEM MERCADORIA','');
insert into atividades (codigo, atividade, observacao) values ('350','FABRICA EM MONTAGEM SEM MERCADORIA','');
insert into atividades (codigo, atividade, observacao) values ('352','FABRICA PARADA/DESOCUPADA S/ MERCADORIA','');
insert into atividades (codigo, atividade, observacao) values ('320','FARINHA - BENEFICIAMENTO E MOAGEM','');
insert into atividades (codigo, atividade, observacao) values ('23','FARINHA - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('104','FARMACIA','');
insert into atividades (codigo, atividade, observacao) values ('89','FERRAGEM E FERRAMENTA - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('406','FIBRA ANIMAL - FIACAO/DEMAIS PROCESSOS','');
insert into atividades (codigo, atividade, observacao) values ('407','FIBRA ANIMAL - TECELAGEM','');
insert into atividades (codigo, atividade, observacao) values ('408','FIBRA ARTIFICIAL/SINTETICA - FILAMENTO','');
insert into atividades (codigo, atividade, observacao) values ('409','FIBRA ARTIFICIAL/SINTETICA - TECELAGEM','');
insert into atividades (codigo, atividade, observacao) values ('164','FILATELIA','');
insert into atividades (codigo, atividade, observacao) values ('410','FITAS(TECIDO) - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('130','FITAS/RENDAS/BORDADOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('211','FLORICULTURA','');
insert into atividades (codigo, atividade, observacao) values ('507','FOTOGRAFICOS, ARTIGOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('71','FOTOGRAFO COM REVELACAO','');
insert into atividades (codigo, atividade, observacao) values ('72','FOTOGRAFO SEM REVELACAO','');
insert into atividades (codigo, atividade, observacao) values ('73','FOTOLITO (COMPUTADORIZADO)','');
insert into atividades (codigo, atividade, observacao) values ('321','FRIGORIFICO','Local que produz e conserva o frio com a finalidade de conservar produtos alimentícios ou substâncias que necessitam se manter em baixas temperaturas. O mesmo que CAMARA FRIGORIFICA.');
insert into atividades (codigo, atividade, observacao) values ('322','FRUTA - BENEFICIAMENTO E EMBALAGEM','');
insert into atividades (codigo, atividade, observacao) values ('24','FRUTAS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('439','FUMO - PREPARACAO/BENEFICIAMENTO','');
insert into atividades (codigo, atividade, observacao) values ('532','FUMO BENEFICIADO - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('455','GELO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('214','GELO, LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('488','GESSO, ARTIGO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('165','GRAFICA (CONVENCIONAL)','Impressos em papel, utilizando máquinas tipográficas, rotativas de flexografias ou roto-gravura, utilizando ou não, tintas a base de inflamáveis. O mesmo que TIPOGRAFIA.');
insert into atividades (codigo, atividade, observacao) values ('74','GRAFICA (INFORMATIZADA)','Impressos em papel ou plástico, utilizando apenas processos e equipamentos informatizados (microcomputadores, plooters, impressoras e etc.) sem utilização de tintas a base de inflamáveis.');
insert into atividades (codigo, atividade, observacao) values ('354','GUARDA-CHUVA/SOL - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('90','GUARDA-MOVEIS','');
insert into atividades (codigo, atividade, observacao) values ('100','GUARDA-SOL/CHUVA - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('215','HANGAR','');
insert into atividades (codigo, atividade, observacao) values ('46','HIDROTERAPICO, ESTABELECIMENTO','');
insert into atividades (codigo, atividade, observacao) values ('47','HOSPITAL','');
insert into atividades (codigo, atividade, observacao) values ('355','HOSPITALARES, APARELHO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('48','HOSPITALARES, ARTIGOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('49','HOTEL','');
insert into atividades (codigo, atividade, observacao) values ('216','IGREJA','');
insert into atividades (codigo, atividade, observacao) values ('468','INCINERADOR','');
insert into atividades (codigo, atividade, observacao) values ('77','INFORMATICA, EQUIPAMENTO - OFICINA','');
insert into atividades (codigo, atividade, observacao) values ('76','INFORMATICA, EQUIPAMENTO-LOJA/ DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('75','INFORMATICA, ESCOLA','');
insert into atividades (codigo, atividade, observacao) values ('78','INFORMATICA, SUPRIMENTO - LOJA/ DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('218','INSTITUTO DE BELEZA','');
insert into atividades (codigo, atividade, observacao) values ('79','INSTRUMENTO CIENTIFICO - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('338','INSTRUMENTO CIENTIFICO/PRECISAO-FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('80','INSTRUMENTO DE PRECISAO - LOJA/ DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('512','INTERNET,CAFE','');
insert into atividades (codigo, atividade, observacao) values ('149','JET SKI - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('469','JOALHERIA - LOJA/DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('219','JOGO, SALAO DE','');
insert into atividades (codigo, atividade, observacao) values ('466','JOIAS - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('440','JORNAIS - OFICINA/IMPRESSAO','');
insert into atividades (codigo, atividade, observacao) values ('166','JORNAIS E REVISTAS - EXCETO BANCAS','');
insert into atividades (codigo, atividade, observacao) values ('106','LABORATORIO DE ANALISE','');
insert into atividades (codigo, atividade, observacao) values ('107','LABORATORIO FARMACEUTICO','');
insert into atividades (codigo, atividade, observacao) values ('81','LABORATORIO FOTOGRAFICO','');
insert into atividades (codigo, atividade, observacao) values ('108','LABORATORIO QUIMICO','');
insert into atividades (codigo, atividade, observacao) values ('458','LADRILHO/AZULEJO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('26','LANCHONETE','');
insert into atividades (codigo, atividade, observacao) values ('324','LATICINIO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('27','LATICINIOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('140','LAVANDERIA DE ROUPAS E TECIDO','');
insert into atividades (codigo, atividade, observacao) values ('325','LEITE - USINA','');
insert into atividades (codigo, atividade, observacao) values ('109','LIMPEZA, MATERIAL - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('126','LINGERIE/ESPARTILHOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('411','LINHA PARA COSTURA - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('141','LINHA,LA E FIOS TEXTEIS-LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('167','LIVRARIA','');
insert into atividades (codigo, atividade, observacao) values ('498','LIVROS - FABRICA E ENCADERNADORA','');
insert into atividades (codigo, atividade, observacao) values ('156','LOCADORA DE FITAS (K7/VHS,GAME,DVD)','');
insert into atividades (codigo, atividade, observacao) values ('249','LOJA DE DEPARTAMENTOS','');
insert into atividades (codigo, atividade, observacao) values ('413','LONA E OLEADOS - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('412','LONA, ARTIGO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('131','LONA, ARTIGOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('60','LOTERICA','');
insert into atividades (codigo, atividade, observacao) values ('428','LOUCA, ARTIGO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('157','LOUCA, ARTIGOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('91','MADEIRA, ARTIGOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('522','MALHARIA, CONFECCAO','');
insert into atividades (codigo, atividade, observacao) values ('93','MAQUINA, GRANDE - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('94','MAQUINA, LEVE/ESCRITORIO-LOJA/ DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('95','MAQUINA, OPERATRIZES - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('92','MAQUINA, PEQUENA E MEDIA-LOJA/DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('224','MARINA','');
insert into atividades (codigo, atividade, observacao) values ('225','MARMORARIA','');
insert into atividades (codigo, atividade, observacao) values ('326','MASSA ALIMENTICIA - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('28','MASSAS ALIMENTICIAS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('327','MATADOURO - INDUSTRIALIZACAO','Abate de animais, separação de vísceras e cortes de carnes. O mesmo que ABATEDOURO.');
insert into atividades (codigo, atividade, observacao) values ('226','MATERIAL DE CONSTRUCAO - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('248','MATERIAL ELETRICO - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('414','MEIA - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('132','MEIA - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('541','METAL NÃO FERROSO, ARTIGO - FABRICA','Industria de artigos metálicos utilizando alumínio, cobre, níquel, estanho ou qualquer outro metal não ferroso. Permitindo-se pequenos trabalhos de solda na produção ou para manutenção.');
insert into atividades (codigo, atividade, observacao) values ('534','METAL, ARTIGO-FABRICA, COM PROC. A QUENT','Indústria de artigos metálicos de ferro e aço, com processos de solda, forja, fundição e demais processos a quente.');
insert into atividades (codigo, atividade, observacao) values ('533','METAL, ARTIGO-FABRICA, SEM PROC. A QUENT','Indústria de artigos metálicos de ferro e aço, permitindo-se apenas pequenos trabalhos de solda na produção e para manutenção.');
insert into atividades (codigo, atividade, observacao) values ('96','METAL, ARTIGOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('361','METAL, TRATAMENTO TERMO-QUIMICO','Tratamento térmico (têmpera, recozimento, etc.) ou químico (niquelação, galvanoplastia, etc.) em artigos metálicos.');
insert into atividades (codigo, atividade, observacao) values ('328','MOINHO - MOAGEM E SILO','');
insert into atividades (codigo, atividade, observacao) values ('362','MOLDURA - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('97','MOLDURA, MONTAGEM - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('50','MOTEL','');
insert into atividades (codigo, atividade, observacao) values ('150','MOTOCICLETA - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('151','MOTOCICLETA - OFICINA','');
insert into atividades (codigo, atividade, observacao) values ('101','MÓVEIS - LOJA E DEPÓSITO','');
insert into atividades (codigo, atividade, observacao) values ('380','MUSICA, INSTRUMENTO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('98','MUSICAL, INSTRUMENTO - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('220','NUMISMATICA','');
insert into atividades (codigo, atividade, observacao) values ('99','OFICINA, MANUTENCAO - GERAL','Qualquer oficina de conserto em aparelhos ou objetos sem especificação definida.');
insert into atividades (codigo, atividade, observacao) values ('460','OLARIA','');
insert into atividades (codigo, atividade, observacao) values ('381','OLEO COMESTIVEL - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('30','OLEO COMESTIVEL - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('382','OLEO LUBRIFICANTE - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('111','OLEO LUBRIFICANTE - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('364','ORTOPEDICO, APARELHO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('51','ORTOPEDICOS, ARTIGOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('461','OSSOS E CHIFRES, ARTIGO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('82','OTICA - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('489','OURIVES','');
insert into atividades (codigo, atividade, observacao) values ('31','PADARIA','');
insert into atividades (codigo, atividade, observacao) values ('329','PANIFICACAO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('442','PAPEL CARBONO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('493','PAPEL, ARTIGO - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('475','PAPEL, DEPOSITO - BOBINAS/FARDOS/RESMAS','');
insert into atividades (codigo, atividade, observacao) values ('444','PAPEL/PAPELAO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('443','PAPEL/PAPELAO, ARTIGO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('168','PAPELARIA - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('222','PARQUE, DIVERSAO OU TEMATICO','');
insert into atividades (codigo, atividade, observacao) values ('223','PEDAGIO','');
insert into atividades (codigo, atividade, observacao) values ('241','PEIXARIA','');
insert into atividades (codigo, atividade, observacao) values ('240','PENSAO','');
insert into atividades (codigo, atividade, observacao) values ('392','PERFUMARIA - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('110','PERFUMARIA - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('227','PET-SHOP','Comércio dos mais diversos produtos para animais de estimação, podendo ou não ter consultório veterinário.');
insert into atividades (codigo, atividade, observacao) values ('462','PINTURA - OFICINA','');
insert into atividades (codigo, atividade, observacao) values ('158','PINTURA, FAIXAS','');
insert into atividades (codigo, atividade, observacao) values ('508','PIZZARIA','');
insert into atividades (codigo, atividade, observacao) values ('536','PLASTICO,ARTIGO-FABRICA S/ RECICLAGEM','');
insert into atividades (codigo, atividade, observacao) values ('537','PLASTICO,EMBALAGEM-FABRICA S/INFLAMAVEL','');
insert into atividades (codigo, atividade, observacao) values ('445','PNEUS E CAMARAS DE AR - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('169','PNEUS E CAMARAS DE AR, LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('170','PNEUS E CAMARAS DE AR, OFICINA','');
insert into atividades (codigo, atividade, observacao) values ('464','PO DE PEDRA - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('228','PORTO','');
insert into atividades (codigo, atividade, observacao) values ('229','POSTO DE SERVICO, COM VENDA DE COMB.','');
insert into atividades (codigo, atividade, observacao) values ('230','POSTO DE SERVICO, SEM VENDA DE COMB.','');
insert into atividades (codigo, atividade, observacao) values ('59','POUSADA','');
insert into atividades (codigo, atividade, observacao) values ('330','PRODUTO ALIMENTICIO - ORIGEM ANIMAL','');
insert into atividades (codigo, atividade, observacao) values ('331','PRODUTO ALIMENTICIO - ORIGEM VEGETAL','');
insert into atividades (codigo, atividade, observacao) values ('32','PRODUTOS ALIMENTICIOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('112','PRODUTOS DE LIMPEZA - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('113','PRODUTOS FARMACEUTICOS SEM INFLAMAVEL','');
insert into atividades (codigo, atividade, observacao) values ('114','PRODUTOS QUIMICOS SEM INFLAMAVEL','');
insert into atividades (codigo, atividade, observacao) values ('245','PROTESE DENTARIA - OFICINA','');
insert into atividades (codigo, atividade, observacao) values ('231','QUARTEL','');
insert into atividades (codigo, atividade, observacao) values ('33','QUITANDA','');
insert into atividades (codigo, atividade, observacao) values ('332','RACAO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('83','RADIO - EMISSORA','');
insert into atividades (codigo, atividade, observacao) values ('519','RADIOLOGIA, CLINICA E CONSULTORIO','');
insert into atividades (codigo, atividade, observacao) values ('509','REFEICOES - ENTREGA','');
insert into atividades (codigo, atividade, observacao) values ('242','RELIGIOSO,ARTIGO - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('473','RELOGIOS - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('472','RELOJOARIA - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('415','RENDA - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('34','RESTAURANTE','');
insert into atividades (codigo, atividade, observacao) values ('467','REVISTA - OFICINA/ IMPRESSAO','');
insert into atividades (codigo, atividade, observacao) values ('171','REVISTAS E JORNAIS, LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('35','ROTISSERIE','');
insert into atividades (codigo, atividade, observacao) values ('416','ROUPA - FABRICA E OFICINA','');
insert into atividades (codigo, atividade, observacao) values ('134','ROUPA - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('385','SABAO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('386','SABONETE - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('387','SAL - EXTRACAO E BENEFICIAMENTO','');
insert into atividades (codigo, atividade, observacao) values ('232','SANITARIO, ARTIGOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('388','SAPONACEO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('52','SAUNA','');
insert into atividades (codigo, atividade, observacao) values ('36','SECOS E MOLHADOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('135','SHOPPING CENTER','');
insert into atividades (codigo, atividade, observacao) values ('333','SORVETE - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('37','SORVETERIA - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('38','SUPERMERCADO/HIPERMERCADO','');
insert into atividades (codigo, atividade, observacao) values ('503','TABACARIA - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('417','TAPETE - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('137','TAPETE - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('233','TEATRO','');
insert into atividades (codigo, atividade, observacao) values ('542','TECIDO - CORTE','Corte de tecidos para confecção em geral, sendo permitido somente máquinas e equipamentos para corte.');
insert into atividades (codigo, atividade, observacao) values ('138','TECIDO - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('234','TELEFERICO','');
insert into atividades (codigo, atividade, observacao) values ('339','TELEFONE - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('84','TELEFONE - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('85','TELEVISAO - EMISSORA','');
insert into atividades (codigo, atividade, observacao) values ('334','TEMPERO - PREPARACAO E EMBALAGEM','');
insert into atividades (codigo, atividade, observacao) values ('235','TEMPLO','');
insert into atividades (codigo, atividade, observacao) values ('389','TINTA, SEM INFLAMAVEL - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('236','TINTAS E VERNIZES, LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('139','TINTURARIA DE ROUPAS E TECIDOS','');
insert into atividades (codigo, atividade, observacao) values ('172','TIPOGRAFIA','Impressos em papel, utilizando máquinas tipográficas, rotativas de flexografias ou roto-gravura, utilizando ou não, tintas a base de inflamáveis.');
insert into atividades (codigo, atividade, observacao) values ('115','TOUCADOR, ARTIGOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('371','TOUCADOR,ARTIGO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('39','TRANSPORTADORA','Local que se destina a armazenar bens e mercadorias indiscriminadas, não sendo permitido o depósito de inflamáveis e/ou explosivos, de qualquer tipo ou quantidade, carga e descarga de maneira manual ou com qualquer tipo de veículo, sendo permitido o acesso de veículos no interior do risco.');
insert into atividades (codigo, atividade, observacao) values ('479','USINA DE CONCRETO','');
insert into atividades (codigo, atividade, observacao) values ('237','VELA, LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('494','VELORIO','');
insert into atividades (codigo, atividade, observacao) values ('430','VIDRO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('490','VIDRO, ARTIGO - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('160','VIDRO, ARTIGOS - LOJA E DEPOSITO','');
insert into atividades (codigo, atividade, observacao) values ('391','VINAGRE - FABRICA','');
insert into atividades (codigo, atividade, observacao) values ('335','VINHO - FABRICA','');


update atividades 
set bloqueado = false,
created_at = current_timestamp::timestamp without time zone,
updated_at = current_timestamp::timestamp without time zone;"
  end

  def self.down
  end
end
